//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langtang.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HimalDbEntities : DbContext
    {
        public HimalDbEntities()
            : base("name=HimalDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LookupIdentifier> LookupIdentifiers { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<ProfileIdentifier> ProfileIdentifiers { get; set; }
        public virtual DbSet<OdsPerson> OdsPersons { get; set; }
        public virtual DbSet<Personnel1> Personnel1 { get; set; }
        public virtual DbSet<Personnel2> Personnel2 { get; set; }
        public virtual DbSet<vPersonnel> vPersonnels { get; set; }
    
        public virtual ObjectResult<TestProc_Result> TestProc(string stringSearch)
        {
            var stringSearchParameter = stringSearch != null ?
                new ObjectParameter("stringSearch", stringSearch) :
                new ObjectParameter("stringSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TestProc_Result>("TestProc", stringSearchParameter);
        }
    
        public virtual int spSaveProfile(string sourceSystem, string dataSet, Nullable<int> profileID, string lastName, string firstName, string middleName, string dODID, string sSN)
        {
            var sourceSystemParameter = sourceSystem != null ?
                new ObjectParameter("SourceSystem", sourceSystem) :
                new ObjectParameter("SourceSystem", typeof(string));
    
            var dataSetParameter = dataSet != null ?
                new ObjectParameter("DataSet", dataSet) :
                new ObjectParameter("DataSet", typeof(string));
    
            var profileIDParameter = profileID.HasValue ?
                new ObjectParameter("ProfileID", profileID) :
                new ObjectParameter("ProfileID", typeof(int));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var dODIDParameter = dODID != null ?
                new ObjectParameter("DODID", dODID) :
                new ObjectParameter("DODID", typeof(string));
    
            var sSNParameter = sSN != null ?
                new ObjectParameter("SSN", sSN) :
                new ObjectParameter("SSN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSaveProfile", sourceSystemParameter, dataSetParameter, profileIDParameter, lastNameParameter, firstNameParameter, middleNameParameter, dODIDParameter, sSNParameter);
        }
    }
}
