//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langtang.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileIdentifier
    {
        public int ProfileIdentifierID { get; set; }
        public int ProfileID { get; set; }
        public short TypeID { get; set; }
        public string Identifier { get; set; }
        public int EventID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
