//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langtang.DataAccessLayer.SSO_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup
    {
        public int LookupID { get; set; }
        public int LookupTypeID { get; set; }
        public bool IsActive { get; set; }
        public int DisplayOrder { get; set; }
        public string Identifier { get; set; }
        public string Descr { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual LookupType LookupType { get; set; }
    }
}
