//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langtang.DataAccessLayer.SSO_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLookup
    {
        public string LookupType { get; set; }
        public int LookupID { get; set; }
        public int DisplayOrder { get; set; }
        public string Identifier { get; set; }
        public string Descr { get; set; }
    }
}
